tinyMCE.addI18n('fr.Archiv',{
	Fdesc : "Insérer un fichier",
	Idesc : "Insérer une image",
	ErrorLoadingTree: "Erreur lors de la lecture de la structure du dossier!",
	NoFiles : "Ce dossier ne contient aucun fichier!",
	ErrorLoadingDirContent : "Erreur lors du chargement du contenu du dossier!",
	FileDelete : "Supprimmer fichier",
	FileName: "Nom",
	FileType: "Type",
	FileSize: "Taille",
	FileDimentions: "Dimenssions",
	FileInfo : "Info de Fichier",
	FileClickToAdd: "Cliquer pour ajouter",
	ErrorAddingFolder : "Erreur lors de l\'ajout du dossier!",
	ErrorDeletingFile : "Erreur lors de la suppression du fichier!",
	ErrorDeletingFolder : "Erreur lors de la suppression du dossier!",
	QuestionFolderName : "Merci d\'entrer un nom pour le dossier",
	QuestionPassword : "Merci d'entrer votre mot de passe",
	ErrorReadingSettingsFile : "Erreur lors de la lecture de la configuration!",
	ConfirmDeleteFile : "Etes vous sûre de vouloir supprimmer ce fichier",
	ConfirmDeleteFolder : "Etes vous sûre de vouloir supprimmer ce dossier"	
});
